config/routes.rb
Rails.application.routes.draw do
  get 'version', to: 'version#index'
  resources :users do
    get :image, on: :member
  end
  resources :circles
  resources :filter_groups do
    resources :filters, only: [:update, :destroy]
  end
  resources :filters
  resources :repos do
    resources :repo_creds, only: [:create, :update, :destroy]
  end
  devise_for :db_users, controllers: {
    sessions: 'db_users/sessions',
    registrations: 'db_users/registrations',
    passwords: 'db_users/passwords'
  }
  devise_for :ldap_users, controllers: {
    sessions: 'ldap_users/sessions',
    registrations: 'ldap_users/registrations',
    passwords: 'ldap_users/passwords'
  }
  resources :profiles, except: [:new] do
    resources :depends, only: [:create, :destroy]
    resources :supports, only: [:create, :destroy]
    resources :controls, except: [:index]
    resources :profile_attributes, except: [:index]
    resources :groups, except: [:edit, :index]
    post 'upload', on: :collection
  end
  resources :evaluations, only: [:index, :show, :destroy] do
    resources :results, only: [:index, :show]
    resources :downloads, only: [:show]
    get 'ssp', on: :member
    get 'partition', on: :member
    post 'filter', on: :member
    post 'filter_select', on: :member
    get 'clear_filter', on: :member
    post 'upload', on: :collection
    post 'upload_api', on: :collection
  end

  match 'session/new_session' => 'users#new_session', as: :new_user_session, :via => :get
  match 'circles/:id/members' => 'circles#members', as: :circle_members, :via => :post
  match 'circles/:id/remove_member/:user_id' => 'circles#remove_member', as: :circle_member_remove, :via => :delete
  match 'circles/:id/owners' => 'circles#owners', as: :circle_owners, :via => :post
  match 'circles/:id/remove_owner/:user_id' => 'circles#remove_owner', as: :circle_owner_remove, :via => :delete
  match 'circles/:id/evals' => 'circles#evaluations', as: :circle_evals, :via => :post
  match 'circles/:id/remove_eval/:evaluation_id' => 'circles#remove_evaluation', as: :circle_eval_remove, :via => :delete
  match 'circles/:id/profiles' => 'circles#profiles', as: :circle_profiles, :via => :post
  match 'circles/:id/remove_profile/:profile_id' => 'circles#remove_profile', as: :circle_profile_remove, :via => :delete
  match 'profiles/:profile_id/controls/:id/details(/evaluation/:evaluation_id)' => 'controls#details', as: :profile_control_details, :via => :get
  match 'profiles/:profile_id/groups/:id/add' => 'groups#add', as: :profile_group_add, :via => :patch
  match 'profiles/:profile_id/groups/:id/remove/:control_id' => 'groups#remove', as: :profile_group_remove, :via => :patch
  match 'profiles/:id/nist(/category/:category)' => 'profiles#nist', as: :profile_nist, :via => :get
  match 'evaluation_upload_api' => 'evaluations#upload_api', as: :upload_evaluation_api, :via => :post
  match 'evaluations/:id/nist(/category/:category)(/status/:status_symbol)' => 'evaluations#nist', as: :evaluation_nist, :via => :get
  match 'evaluations/:id/xccdf' => 'evaluations#xccdf', as: :evaluation_xccdf, :via => :get
  match 'evaluations/:id/xccdf' => 'evaluations#create_xccdf', as: :evaluation_create_xccdf, :via => :post
  match 'evaluations/:id/csv' => 'evaluations#csv', as: :evaluation_csv, :via => :get
  match 'evaluations_compare' => 'evaluations#compare', as: :evaluations_compare, :via => [:get, :post]
  match 'evaluations/:id/tag' => 'evaluations#tag', as: :evaluation_tag, :via => :post
  match 'evaluations/:id/chart' => 'evaluations#chart', as: :evaluation_chart, :via => :get
  match 'users/:id/add_role/:user_id/' => 'users#add_role', as: :user_add_role, :via => :post
  match 'users/:id/remove_role/:user_id/:role' => 'users#remove_role', as: :user_remove_role, :via => :delete

  root to: 'dashboard#index'
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  load_resource
  authorize_resource only: [:show, :partition, :destroy, :upload, :filter, :clear_filter, :tag, :new_xccdf]
  protect_from_forgery except: [:upload_api]

  # GET /evaluations
  # GET /evaluations.json
  def index
    if current_user
      @evaluations = current_user.readable_evaluations
    else
      @circle = Circle.where(name: 'Public').try(:first)
      @evaluations = @circle.present? ? @circle.evaluations : []
    end
    user_ids = @evaluations.map(&:created_by_id)
    @users = User.in(id: user_ids)
    @users = @users.index_by(&:id)
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
    @profiles = @evaluation.profiles
    filters, @filter_label = session_filters
    # @counts = Rails.cache.read("counts:#{@evaluation.id}")
    # @controls = Rails.cache.read("controls:#{@evaluation.id}")
    # unless @counts
    #  @counts, @controls = @evaluation.status_counts(filters)
    #  Rails.cache.write "counts:#{@evaluation.id}", @counts
    #  Rails.cache.write "controls:#{@evaluation.id}", @controls
    # end
    @nist_hash = Constants::NIST_800_53
    respond_to do |format|
      format.html { render :show }
      format.json { render :show }
      format.ckl { render :show, layout: false }
      format.csv { render :show, layout: false }
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def chart
    if params['chart_type']
      @chart_type = params['chart_type']
    else
      @chart_type = 'treemap'
    end
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def ssp
    authorize! :read, Evaluation
    @nist_hash = Constants::NIST_800_53
    @symbols = @evaluation.symbols
    @evaluation.profiles.each do |profile|
      families, nist = profile.control_families
      next if families.empty?

      @nist_hash['children'].each do |cf|
        family_value = 0
        cf['children'].each do |control|
          if families.include?(control['name'])
            control['controls'] = nist[control['name']]
            control['value'] = control['controls'].size
            family_value += control['controls'].size
          else
            control['value'] = 0
          end
        end
        cf['value'] = family_value
      end
    end
  end

  def nist
    authorize! :read, Evaluation
    filters, = session_filters
    category = nil
    category = params[:category].downcase if params.key?(:category)
    status_sym = nil
    status_sym = params[:status_symbol].downcase.tr(' ', '_').to_sym if params.key?(:status_symbol)
    ex_ids = params[:ex_ids]
    ex_ids = [] if ex_ids.nil?
    # key = "#{params[:id]}#{category}|#{status_sym}|#{filters}"
    # @control_hash = Rails.cache.read(key)
    @control_hash = nil
    @control_hash ||= @evaluation.nist_hash category, status_sym, ex_ids, filters
    @name = Constants::NIST_800_53['name']
    @families = Constants::NIST_800_53['children']
  end

  def clear_filter
    session[:filter] = nil
    session[:filter_group] = nil
    redirect_to @evaluation
  end

  def filter
    f_params = params[:filter]
    @filter = Filter.valid_filter f_params
    if f_params[:save_filter]
      @filter.save
    end
    session[:filter] = @filter
    session[:filter_group] = nil
    redirect_to @evaluation
  end

  def filter_select
    filter_params = params[:filter_group]
    if filter_params[:id].present?
      @filter_group = FilterGroup.find(filter_params[:id])
      session[:filter] = nil
      session[:filter_group] = @filter_group
    elsif filter_params[:filter_ids].present?
      @filter = Filter.find(filter_params[:filter_ids])
      session[:filter_group] = nil
      session[:filter] = @filter
    end
    redirect_to @evaluation
  end

  def tag
    @evaluation.tags.where(name: tag_params['name'])&.destroy
    @evaluation.tags.create(name: tag_params['name'], value: tag_params['value'])
    redirect_to @evaluation
  end

  def upload
    authorize! :create, Evaluation
    file = params[:file]
    if (@eval = Evaluation.parse(JSON.parse(file.read)))
      @evaluation = Evaluation.find(@eval.id)
      @evaluation.tags.create(name: 'filename', value: params[:file].original_filename)
      (Constants::TAG_NAMES - ['Filename']).each do |tag|
        if params[tag.downcase]
          @evaluation.tags.create(name: tag.downcase, value: params[tag.downcase])
        end
      end
      redirect_to @evaluation, notice: 'Evaluation uploaded.'
    else
      redirect_to evaluations_url, notice: 'File does not contain an evaluation.'
    end
  end

  def upload_api
    file = params[:file]
    sign_in_api_user(params[:email], params[:api_key])
    if current_user
      authorize! :create, Evaluation
      if (@eval = Evaluation.parse(JSON.parse(file.read)))
        @eval.force_created_by(current_user)
        @evaluation = Evaluation.find(@eval.id)
        @evaluation.tags.create(name: 'filename', value: params[:file].original_filename)
        (Constants::TAG_NAMES - ['Filename']).each do |tag|
          if params[tag.downcase]
            @evaluation.tags.create(name: tag.downcase, value: params[tag.downcase])
          end
        end
        render body: 'SUCCESS: Evaluation uploaded'
      else
        render body: 'ERROR: Could not upload evaluation'
      end
    else
      render body: 'ERROR: Could not login User'
    end
  end

  def compare
    if params[:evaluation] && params[:evaluation][:eval_ids]
      eval_params = params[:evaluation][:eval_ids]
      @evaluations = []
      @compare_hsh = {}
      eval_params.each do |eval_id|
        evaluation = Evaluation.find(eval_id)
        @evaluations << evaluation
        _, controls = evaluation.status_counts
        controls.each do |_, hsh|
          control = hsh[:control]
          unless @compare_hsh.key?(control.control_id)
            @compare_hsh[control.control_id] = {}
          end
          @compare_hsh[control.control_id][evaluation.id] = hsh
        end
      end
    else
      redirect_to evaluations_url
    end
  end

  def xccdf
    @xccdf = Xccdf.new
  end

  def create_xccdf
    @attribs = {}
    @attribs['benchmark.title'] = xccdf_params[:benchmark_title]
    @attribs['benchmark.id'] = xccdf_params[:benchmark_id]
    @attribs['benchmark.description'] = xccdf_params[:benchmark_description]
    @attribs['benchmark.version '] = xccdf_params[:benchmark_version]
    @attribs['benchmark.status'] = xccdf_params[:benchmark_status]
    @attribs['benchmark.status.date'] = xccdf_params[:benchmark_status_date]
    @attribs['benchmark.notice'] = xccdf_params[:benchmark_notice]
    @attribs['benchmark.notice.id'] = xccdf_params[:benchmark_notice_id]
    @attribs['benchmark.plaintext'] = xccdf_params[:benchmark_plaintext]
    @attribs['benchmark.plaintext.id'] = xccdf_params[:benchmark_plaintext_id]
    @attribs['reference.href'] = xccdf_params[:reference_href]
    @attribs['reference.dc.source'] = xccdf_params[:reference_dc_source]
    @attribs['reference.dc.publisher'] = xccdf_params[:reference_dc_publisher]
    @attribs['reference.dc.title'] = xccdf_params[:reference_dc_publisher]
    @attribs['reference.dc.subject'] = xccdf_params[:reference_dc_subject]
    @attribs['reference.dc.type'] = xccdf_params[:reference_dc_type]
    @attribs['reference.dc.identifier'] = xccdf_params[:reference_dc_identifier]
    @attribs['content_ref.href'] = xccdf_params[:content_ref_href]
    @attribs['content_ref.name'] = xccdf_params[:content_ref_name]
    Rails.logger.debug "Attributes: #{@attribs.inspect}"
    render xml: @evaluation.to_xccdf(@attribs), layout: false
  end

  private

  def sign_in_api_user(email, api_key)
    if (user = User.where(email: email, api_key: api_key).first)
      sign_in user
      if user._type == 'DbUser'
        session['user_id'] = session['warden.user.db_user.key'].first.try(:first)
      elsif user._type == 'LdapUser'
        session['user_id'] = session['warden.user.ldap_user.key'].first.try(:first)
      end
    end
  end

  def session_filters
    filters = nil
    filter_label = nil
    if session[:filter]
      filter = session[:filter].is_a?(Filter) ? session[:filter] : Filter.new(session[:filter])
      filters = [filter]
      filter_label = filter.to_s
    elsif session[:filter_group]
      filter_group = session[:filter_group].is_a?(FilterGroup) ? session[:filter_group] : FilterGroup.new(session[:filter_group])
      filters = filter_group.filters
      filter_label = "#{filter_group.name}: #{filter_group.filters.map(&:to_s).join(', ')}"
    end
    [filters, filter_label]
  end

  def tag_params
    params.require(:tag).permit(:name, :value)
  end

  def xccdf_params
    params.require(:xccdf).permit(:benchmark_title, :benchmark_id, :benchmark_description, :benchmark_version, :benchmark_status, :benchmark_status_date, :benchmark_notice, :benchmark_notice_id, :benchmark_plaintext, :benchmark_plaintext_id, :reference_href, :reference_dc_source, :reference_dc_publisher, :reference_dc_title, :reference_dc_subject, :reference_dc_type, :reference_dc_identifier, :content_ref_href, :content_ref_name, :plaintext_notice, :plaintext_notice_id)
  end
end

app/views/evaluations/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Evaluations
  </h1>
  <ol class="breadcrumb">
    <li><%= link_to ('<i class="fa fa-dashboard"> </i>Dashboard').html_safe, root_path %></li>
    <li class="active">Evaluations</li>
  </ol>
</section>

<section class="content container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Evaluations</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <%= form_for :evaluation, url: evaluations_compare_path do |form| %>
          <table class="table table-hover">
            <tr>
              <th>Profiles</th>
              <th>Filename</th>
              <th>Start Time</th>
              <th>Duration</th>
              <th>InSpec Version</th>
              <th>Platform Name</th>
              <th>Platform Release</th>
              <th>Compliance</th>
              <th>Compare</th>
              <th>Owner</th>
              <th></th>
            </tr>

            <% @evaluations.each do |evaluation| %>
              <tr>
                <td><%= link_to evaluation.profiles.map(&:name).join(', '), evaluation %></td>
                <td><%= evaluation.tags.where(name: 'filename').first&.value %></td>
                <td><%= evaluation.start_time %></td>
                <td><%= evaluation.statistics_duration %></td>
                <td><%= evaluation.version %></td>
                <td><%= evaluation.platform_name %></td>
                <td><%= evaluation.platform_release %></td>
                <td>
                  <table id="message_counts" class="cn-msg-table">
                    <tr>
                      <td><div class="cn-msg-bar bg-green" data-status="0" style="width: <%= pass_pixels(evaluation.findings) %>px"></div></td>
                      <td><div class="cn-msg-bar bg-red" data-status="3" style="width: <%= fail_pixels(evaluation.findings) %>px"></div></td>
                    </tr>
                  </table>
                </td>
                <td>
                  <div class="checkbox">
                    <label>
                      <%= form.check_box 'eval_ids', {:checked=>false, :multiple => true}, evaluation.id, nil %>
                    </label>
                  </div>
                </td>
                <td><%= @users[evaluation.created_by_id].try(:email) %></td>
                <td><% if can? :delete, evaluation %><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
              </tr>
            <% end %>
            <tr>
              <td colspan='7'></td>
              <td>
                <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                  <i class="fa fa-edit"></i> Compare
                <% end %>
              </td>
              <td colspan='2'></td>
            </tr>
          </table>
          <% end %>
        </div>
      </div>
    </div>
    <% if can? :create, Evaluation %>
      <div class="col-xs-6">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Upload Evaluation</h3>
          </div>
          <div class="box-body">
            <%= form_tag(upload_evaluations_path, multipart: true, :html => {class: 'form-control'}) do %>
              <div class="input-group">
                <%= file_field_tag :file, :class => "menu-text" %>
              </div>
              <br>
              <% (Constants::TAG_NAMES - ['Filename', 'Environment']).each do |tag| %>
                <div class="form-group">
                  <%= label_tag(tag, "#{tag}:") %>
                  <%= text_field_tag(tag.downcase) %>
                </div>
              <% end %>
              <div class="form-group">
                <%= label_tag(:environment, 'Environment:') %>
                <%= select_tag :environment, options_for_select(Constants::ENV_TAG_NAMES), include_blank: true %>
              </div>
              <div class="actions">
                <%= submit_tag 'Upload', :class => "btn btn-info" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>
<!-- /.content -->

app/views/evaluations/ssp.html.erb
<style>
.scroll-nav {
  position: absolute;
}
.scroll-nav.fixed .scroll-nav__wrapper {
  position: fixed;
  top: 60px;
}

.scroll-nav__wrapper {
  border: 1px solid #006f99;
  background-color: #1e8cb7;
  border-radius: 6px;
  padding: 10px 5px;
}

.scroll-nav__heading {
  border-bottom: 2px solid #fff;
  color: #fff;
  display: block;
  font-family: "Alfa Slab One", Georgia, serif;
  font-size: 1.2em;
  margin-bottom: 15px;
  overflow: hidden;
  padding-bottom: 10px;
  padding-top: 10px;
  text-align: center;
  text-shadow: 0 -1px 0 #006186;
  width: 40px;
}
.scroll-nav__heading:before {
  font-size: 40px;
}

.scroll-nav__list {
  margin-bottom: 0;
}

.scroll-nav__item {
  font-weight: 600;
  font-size: 30px;
  line-height: 1.2em;
  margin: 0 auto;
  overflow: hidden;
  width: 40px;
}
.scroll-nav__item:before {
  color: #fff;
  display: block;
  position: absolute;
  pointer-events: none;
  text-align: center;
  width: 40px;
}
.scroll-nav__item.active {
  -webkit-transform: scale(1.3, 1.3);
  -moz-transform: scale(1.3, 1.3);
  -ms-transform: scale(1.3, 1.3);
  -o-transform: scale(1.3, 1.3);
  transform: scale(1.3, 1.3);
  font-weight: 800;
}
.scroll-nav__item.active a:hover {
  font-weight: 800;
}

.scroll-nav__link {
  color: #fff;
  display: block;
  margin: 0 auto;
  padding-left: 42px;
}
.scroll-nav__link:hover {
  color: #fff;
}
.scroll-nav__wrapper {
    padding: 15px 10px;
  }

  .scroll-nav__heading {
    font-size: 1.7em;
    text-indent: -16px;
    width: 170px;
  }
  .scroll-nav__heading:before {
    font-size: 1.654411765em;
    position: relative;
    right: -0.30em;
    top: -0.07em;
  }

  .scroll-nav__item {
    font-size: 19px;
    line-height: 1.4em;
    overflow: visible;
    width: 170px;
  }
  .scroll-nav__item.active {
    -webkit-transform: scale(1.2, 1.2);
    -moz-transform: scale(1.2, 1.2);
    -ms-transform: scale(1.2, 1.2);
    -o-transform: scale(1.2, 1.2);
    transform: scale(1.2, 1.2);
    padding-left: 0.5em;
  }
  .scroll-nav__item:before {
    width: 30px;
  }

  .scroll-nav__link {
    padding-left: 30px;
  }

</style>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Evaluation <%= link_to @evaluation.profiles.map(&:name).join(', '), evaluation_path(@evaluation.id) %></h1>
  <ol class="breadcrumb" data-turbolinks="false">
    <li><%= link_to ('<i class="fa fa-dashboard"> </i>Dashboard').html_safe, home_path %></li>
    <li><%= link_to 'Evaluations', evaluations_path %></li>
    <li><%= link_to 'Evaluation', evaluation_path(@evaluation.id) %></li>
    <li class="active">SSP</li>
  </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
  <div class="row body">
    <div class="col-md-9">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h1 class="box-title">SSP Ready Control Implementation Details and Status</h1>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <% counts, _ = @evaluation.status_counts %>
          <% total_count = counts[:open] + counts[:not_a_finding] + counts[:not_reviewed] + counts[:not_tested] + counts[:not_applicable] %>
          <% compliance_level = ((counts[:not_a_finding] + counts[:not_applicable]).to_f / total_count) * 100 %>
          <h2>Compliance Level: <%= compliance_level.round(1) %>%</h2>
          <div class="container-fluid">
            <div class="row">
              <div class="col-xs-3">
                <h4>Not a Finding: <%= counts[:not_a_finding] %></h4>
                <h4>Open: <%= counts[:open] %></h4>
              </div>
              <div class="col-xs-3">
                <h4>Not Reviewed: <%= counts[:not_reviewed] %></h4>
                <h4>Not Tested: <%= counts[:not_tested] %></h4>
              </div>
              <div class="col-xs-3">
                <h4>Not Applicable: <%= counts[:not_applicable] %></h4>
              </div>
            </div>
          </div>
          <% @nist_hash["children"].each do |family| %>
            <% if family["value"] > 0 %>
              <h2 id="<%= family['name'] %>"><%= family["name"] %>: <%= family["desc"] %></h2>
              <div class="container-fluid">
                <% family["children"].each do |cf| %>
                  <% if cf["value"] > 0 %>
                    <% cf_name = cf['name'] %>
                    <h3 id="<%= cf_name %>" onclick="togAll('<%= cf_name %>')"><%= cf_name %></h3>
                    <div class="container-fluid big-margin-bottom">
                      <% cf["controls"].each_with_index do |control, index| %>
                        <h4><button class="<%= status_btn(@symbols[control.control_id]) %>" onclick="$('#<%= control.control_id %>').toggle()"><%= @symbols[control.control_id].to_s.titleize %></button> <%= index+1 %>. <%= control.title %></h4>
                        <div id="<%= control.control_id %>" class="container-fluid big-margin-bottom" style="display: none">
                          <%= control.desc %>
                          <h4>Check Text</h4> <pre><%= control.tag('check') %></pre>
                          <h4>Fix Text</h4> <pre><%= control.tag('fix') %></pre>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div id="sidebar" class="box box-primary">
        <div class="box-body">
          <h4><%= link_to "Download as PDF",
            evaluation_download_path(@evaluation, format: "pdf"),
            target: "_blank",
            class: "download" %>
          </h3>
        </div>
      </div>
      <div id="sidebar" class="box box-primary sidebar">
        <ul id="sspList" class="list-unstyled">
          <li onclick='$(window).scrollTop(0);'>Scroll to Top</li>
          <% @nist_hash["children"].each do |family| %>
            <% if family["value"] > 0 %>
              <li id="<%= family['name'] %>">
                <%= family["name"] %>: <%= family["desc"] %>
                <ul class="list-unstyled">
                  <% family["children"].each do |cf| %>
                    <% if cf["value"] > 0 %>
                      <li id="<%= cf['name'] %>"><%= cf["name"] %> <span class="grey-text margin-left">Controls: <%= cf["value"] %></span></li>
                    <% end %>
                  <% end %>
                </ul>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>
<script>
  var families = {};
  <% @nist_hash["children"].each do |family| %>
    <% family["children"].each do |cf| %>
      <% if cf["value"] > 0 %>
        families["<%= cf['name'] %>"] = ["<%= raw cf["controls"].map(&:control_id).join('","') %>"];
      <% end %>
    <% end %>
  <% end %>
  document.addEventListener("turbolinks:load", function() {
    CollapsibleLists.applyTo(document.getElementById('sspList'));
    Prism.highlightAll();
    document.body.scrollTop = 0;
  });

  $.fn.scrollView = function () {
    return this.each(function () {
      $('html, body').animate({
        scrollTop: $(this).offset().top
      }, 1000);
    });
  }

  function togAll(id) {
    console.log("togAll " + id);
    for (ct in families[id]) {
      console.log("control " + families[id][ct]);
      idStr = "#" + families[id][ct];
      $(idStr).toggle();
    }
  }

</script>