config/routes.rb
Rails.application.routes.draw do
  get 'version', to: 'version#index'
  resources :users do
    get :image, on: :member
  end
  resources :circles
  resources :filter_groups do
    resources :filters, only: [:update, :destroy]
  end
  resources :filters
  resources :repos do
    resources :repo_creds, only: [:create, :update, :destroy]
  end
  devise_for :db_users, controllers: {
    sessions: 'db_users/sessions',
    registrations: 'db_users/registrations',
    passwords: 'db_users/passwords'
  }
  devise_for :ldap_users, controllers: {
    sessions: 'ldap_users/sessions',
    registrations: 'ldap_users/registrations',
    passwords: 'ldap_users/passwords'
  }
  resources :profiles, except: [:new] do
    resources :depends, only: [:create, :destroy]
    resources :supports, only: [:create, :destroy]
    resources :controls, except: [:index]
    resources :profile_attributes, except: [:index]
    resources :groups, except: [:edit, :index]
    post 'upload', on: :collection
  end
  resources :evaluations, only: [:index, :show, :destroy] do
    resources :results, only: [:index, :show]
    resources :downloads, only: [:show]
    get 'ssp', on: :member
    get 'partition', on: :member
    post 'filter', on: :member
    post 'filter_select', on: :member
    get 'clear_filter', on: :member
    post 'upload', on: :collection
    post 'upload_api', on: :collection
  end

  match 'session/new_session' => 'users#new_session', as: :new_user_session, :via => :get
  match 'circles/:id/members' => 'circles#members', as: :circle_members, :via => :post
  match 'circles/:id/remove_member/:user_id' => 'circles#remove_member', as: :circle_member_remove, :via => :delete
  match 'circles/:id/owners' => 'circles#owners', as: :circle_owners, :via => :post
  match 'circles/:id/remove_owner/:user_id' => 'circles#remove_owner', as: :circle_owner_remove, :via => :delete
  match 'circles/:id/evals' => 'circles#evaluations', as: :circle_evals, :via => :post
  match 'circles/:id/remove_eval/:evaluation_id' => 'circles#remove_evaluation', as: :circle_eval_remove, :via => :delete
  match 'circles/:id/profiles' => 'circles#profiles', as: :circle_profiles, :via => :post
  match 'circles/:id/remove_profile/:profile_id' => 'circles#remove_profile', as: :circle_profile_remove, :via => :delete
  match 'profiles/:profile_id/controls/:id/details(/evaluation/:evaluation_id)' => 'controls#details', as: :profile_control_details, :via => :get
  match 'profiles/:profile_id/groups/:id/add' => 'groups#add', as: :profile_group_add, :via => :patch
  match 'profiles/:profile_id/groups/:id/remove/:control_id' => 'groups#remove', as: :profile_group_remove, :via => :patch
  match 'profiles/:id/nist(/category/:category)' => 'profiles#nist', as: :profile_nist, :via => :get
  match 'evaluation_upload_api' => 'evaluations#upload_api', as: :upload_evaluation_api, :via => :post
  match 'evaluations/:id/nist(/category/:category)(/status/:status_symbol)' => 'evaluations#nist', as: :evaluation_nist, :via => :get
  match 'evaluations/:id/xccdf' => 'evaluations#xccdf', as: :evaluation_xccdf, :via => :get
  match 'evaluations/:id/xccdf' => 'evaluations#create_xccdf', as: :evaluation_create_xccdf, :via => :post
  match 'evaluations/:id/csv' => 'evaluations#csv', as: :evaluation_csv, :via => :get
  match 'evaluations_compare' => 'evaluations#compare', as: :evaluations_compare, :via => [:get, :post]
  match 'evaluations/:id/tag' => 'evaluations#tag', as: :evaluation_tag, :via => :post
  match 'evaluations/:id/chart' => 'evaluations#chart', as: :evaluation_chart, :via => :get
  match 'users/:id/add_role/:user_id/' => 'users#add_role', as: :user_add_role, :via => :post
  match 'users/:id/remove_role/:user_id/:role' => 'users#remove_role', as: :user_remove_role, :via => :delete

  root to: 'dashboard#index'
end

app/views/layouts/_sidebar.html.erb
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <div data-turbolinks="false">
    <!-- Sidebar user panel (optional) -->

    <!-- search form (Optional) -->
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
      <li>
        <a href="/"><i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>
      <!-- Optionally, you can add icons to the links -->
      <li class="treeview">
        <a href=""><i class="fa fa-edit"></i> <span>Profiles</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><%= link_to "All Profiles", profiles_path %></li>
          <li>
            <%= form_tag(upload_profile_path, multipart: true, :html => {class: 'form-control'}) do %>
              <div class="input-group">
                <%= label_tag :file, "Upload Profile", :class => "menu-text" %>
                <%= file_field_tag :file, :class => "menu-text" %>
              </div>
              <br>
              <div class="actions">
                <%= submit_tag 'Upload', :class => "btn btn-info" %>
              </div>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <a href=""><i class="fa fa-edit"></i> <span>Evaluations</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><%= link_to "All Evaluations", evaluations_path %></li>
          <li>
            <%= form_tag(upload_evaluation_path, multipart: true, :html => {class: 'form-control'}) do %>
              <div class="input-group">
                <%= label_tag :file, "Upload Evaluation", :class => "menu-text" %>
                <%= file_field_tag :file, :class => "menu-text" %>
              </div>
              <br>
              <div class="actions">
                <%= submit_tag 'Upload', :class => "btn btn-info" %>
              </div>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <a href=""><i class="fa fa-edit"></i> <span>Tools</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
          <li><%= link_to "Compliance Mapper", mappings_path %></li>
          </li>
        </ul>
      </li>
    </ul>
  </div>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
  <head>
    <title>Dashboard</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="google" content="notranslate">
    <meta http-equiv="Content-Language" content="en">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="hold-transition skin-blue layout-top-nav">
    <%= favicon_link_tag asset_path('logo_yH1_icon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <div class="wrapper">

      <!-- Main Header -->
      <%= render :partial => 'layouts/header' %>
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" data-turbolinks="false">
        <div class='content'>
          <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %> fade in alert-dismissible">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <%= value %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right">
           <a href="https://github.com/mitre/heimdall/tree/<%= MyApp::VERSION %>"><%= MyApp::VERSION %></a> (<%= MyApp::BRANCH %>)
        </div>
        <strong>Copyright &copy; <%= Date.today.year %> <a href="http://www.mitre.org/">MITRE</a></strong>
      </footer>
    </div>
    <!-- ./wrapper -->
  </body>
</html>